src/account/urls.py
from django.urls import path
from .views import Login, Logout_view, UserList, CreateUser, DisableUser, UserDetail

app_name = 'account'

urlpatterns = [
    path('', Login.as_view(), name='login'),
    path('logout/', Logout_view, name='logout'),
    path('account/', UserList.as_view(), name='user_list'),
    path('account/create/', CreateUser.as_view(), name='create_user'),
    path('account/<int:id>/', UserDetail.as_view(), name='user_detail'),
    path('account/<int:id>/edit/', DisableUser.as_view(), name='disable_user'),

]

src/api/urls.py
from django.urls import path
from .views import Worker_List, CheckStaffPayrollID

app_name = 'api'

urlpatterns = [
    path('worker/<int:event_id>/<str:name>', Worker_List, name='worker_list'),
    path('worker/payroll/<str:payroll_id>/', CheckStaffPayrollID, name='worker_payroll_id'),
]

src/event/urls.py
from django.urls import path
import event.views as v_

app_name = 'event'

urlpatterns = [
    path('', v_.EventListView.as_view(), name='event_list'),
#   Managers
    path('management/', v_.ManagerOptions.as_view(), name='manager_options'),
#   Event
    path('create/', v_.EventCreateView.as_view(), name='create_event'),
    path('<slug:slug>/', v_.EventDetailView.as_view(), name='dashboard'),
    path('<slug:slug>/assign-supplier/', v_.EventAssignSupplier.as_view(), name='assign_supplier'),
    path('<slug:slug>/assign-logistics-user/', v_.EventAssignLogisticsStaff.as_view(), name='assign_logistics_user'),
    path('<slug:slug>/close-event/', v_.EventCloseView.as_view(), name='close_event'),
#   Worker urls below this line
    path('<slug:slug>/worker/', v_.WorkerSearch.as_view(), name='worker_search'),
    path('<slug:slug>/worker/create/', v_.WorkerCreate.as_view(), name='worker_create'),
    path('<slug:slug>/worker/bulk-create/', v_.WorkerBulkCreate.as_view(), name='worker_bulk_create'),
    path('<slug:slug>/worker/<int:id>/', v_.WorkerDetail.as_view(), name='worker_detail'),
    path('<slug:slug>/worker/<int:id>/edit/', v_.WorkerUpdate.as_view(), name='worker_update'),
    path('<slug:slug>/worker/<int:id>/accredit/', v_.WorkerAccredit.as_view(), name='worker_accredit'),
]

src/festival_accreditation/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('company/', include('supplier.urls', namespace='supplier')),
    path('event/', include('event.urls', namespace='event')),
    path('api/', include('api.urls', namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/supplier/urls.py
from django.urls import path
from .views import CompanyList, CompanyCreate, CompanyDisable

app_name = 'supplier'

urlpatterns = [
    path('', CompanyList.as_view(), name='company_list'),
    path('create/', CompanyCreate.as_view(), name='company_create'),
    path('<int:id>/edit/', CompanyDisable.as_view(), name='company_disable'),   
]

src/templates/base.html
{% extends 'core.html' %}
{% load static %}
{% block main %}
    <header>
        <div class="d-flex flex-wrap justify-content-center pt-3 container">
            <a href="{% url 'event:event_list' %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
            <span class="fs-4">Festival Accreditation</span>
            </a>

            {% if request.user.is_authenticated %}
                <ul class="nav nav-pills">
                    {% if request.user.is_manager %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Manager</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'supplier:company_list' %}">Company List</a></li>
                            <li><a class="dropdown-item" href="{% url 'account:user_list' %}">Users</a></li>
                        </ul>
                    </li>
                    {% endif %}
                    <li class="nav-item"><a href="{% url 'event:event_list' %}" class="nav-link">Events</a></li>
                    {% comment %} <li class="nav-item"><a href="#" class="nav-link">Pricing</a></li> {% endcomment %}
                    <li class="nav-item"><a href="{% url 'account:logout' %}" class="nav-link">Logout</a></li>
                </ul>
            {% endif %}
        </div>
    </header>

    <div class="container mt-3">
        <div class="d-flex flex-column bd-highlight mb-3 justify-content-between border-bottom border-primary">
            {% block top %}
        
            {% endblock top %}
            {% for message in messages %}
                <div{% if message.tags == "success" %} class="alert alert-success" 
                {% elif message.tags == "info" %} class="alert alert-info" 
                {% elif message.tags == "warning" %} class="alert alert-warning" {% endif %}>
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>{{message}}
                </div>
            {% endfor%}
        </div>
        
        {% block content %}
        
        {% endblock content %}
    </div>
{%  endblock main %}

src/templates/core.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block css_links %}
        
    {% endblock css_links %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project Festival</title>
</head>
<body>
    
    {% block main %}
    
    
    
    {% endblock main %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    <script src="{% static 'js/app.js' %}" type="text/javascript"></script>
    {% block js_links %}
    {% endblock js_links %}
</body>
</html>