src/api/urls.py
from django.urls import path
from .views import Worker_List, CheckStaffPayrollID

app_name = 'api'

urlpatterns = [
    path('worker/<int:event_id>/<str:name>', Worker_List, name='worker_list'),
    path('worker/payroll/<str:payroll_id>/', CheckStaffPayrollID, name='worker_payroll_id'),
]

src/event/urls.py
from django.urls import path
import event.views as v_

app_name = 'event'

urlpatterns = [
    path('', v_.EventListView.as_view(), name='event_list'),
#   Managers
    path('management/', v_.ManagerOptions.as_view(), name='manager_options'),
#   Event
    path('create/', v_.EventCreateView.as_view(), name='create_event'),
    path('<slug:slug>/', v_.EventDetailView.as_view(), name='dashboard'),
    path('<slug:slug>/assign-supplier/', v_.EventAssignSupplier.as_view(), name='assign_supplier'),
    path('<slug:slug>/assign-logistics-user/', v_.EventAssignLogisticsStaff.as_view(), name='assign_logistics_user'),
    path('<slug:slug>/close-event/', v_.EventCloseView.as_view(), name='close_event'),
#   Worker urls below this line
    path('<slug:slug>/worker/', v_.WorkerSearch.as_view(), name='worker_search'),
    path('<slug:slug>/worker/create/', v_.WorkerCreate.as_view(), name='worker_create'),
    path('<slug:slug>/worker/bulk-create/', v_.WorkerBulkCreate.as_view(), name='worker_bulk_create'),
    path('<slug:slug>/worker/<int:id>/', v_.WorkerDetail.as_view(), name='worker_detail'),
    path('<slug:slug>/worker/<int:id>/edit/', v_.WorkerUpdate.as_view(), name='worker_update'),
    path('<slug:slug>/worker/<int:id>/accredit/', v_.WorkerAccredit.as_view(), name='worker_accredit'),
]

src/festival_accreditation/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('company/', include('supplier.urls', namespace='supplier')),
    path('event/', include('event.urls', namespace='event')),
    path('api/', include('api.urls', namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/supplier/urls.py
from django.urls import path
from .views import CompanyList, CompanyCreate, CompanyDisable

app_name = 'supplier'

urlpatterns = [
    path('', CompanyList.as_view(), name='company_list'),
    path('create/', CompanyCreate.as_view(), name='company_create'),
    path('<int:id>/edit/', CompanyDisable.as_view(), name='company_disable'),   
]

src/templates/management/company_create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css_links %}
    <link rel="stylesheet" href="{% static 'css/worker_details.css' %}">
{% endblock css_links %}

{% block top %}
    <div class="d-flex flex-row bd-highlight mb-3 justify-content-between">
        <div>
            <h4> Create Company </h4>
        </div>
    </div>
{% endblock top %}

{% block content %}

<div class="d-flex">
    <div class="detail-area">
        <form method="Post" action=".">
            {% csrf_token %}
            {{form|crispy}}
            <a href="{% url 'supplier:company_list' %}" class="btn btn-outline-primary mt-3">Cancel</a>
            <input class="btn btn-danger mt-3" type="submit" name="submit" value="Submit">
        </form>
    </div>
</div>

{% endblock content %}

src/templates/management/company_disable.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css_links %}
    <link rel="stylesheet" href="{% static 'css/worker_details.css' %}">
{% endblock css_links %}

{% block top %}
    <div class="d-flex flex-row bd-highlight mb-3 justify-content-between">
        <div>
            {% if object.is_active %}
                <h4>Disable {{object.name|title }} </h4>
            {% else %}
                <h4>Enable {{object.name|title }} </h4>
            {% endif %}
        </div>
    </div>
{% endblock top %}

{% block content %}

<div class="d-flex">
    <div class="detail-area">
        <form method="Post" action=".">
            {% csrf_token %}
            {% if object.is_active %}
                <input type="hidden" id="custId" name="toggle" value="disable">
            {% else %}
                <input type="hidden" id="custId" name="toggle" value="enable">
            {% endif %}
            <p>Are you sure you?</p>
            <a href="{% url 'supplier:company_list' %}" class="btn btn-outline-primary mt-3">Cancel</a>
            <input class="btn btn-danger mt-3" type="submit" name="yes" value="Accept">

        </form>
    </div>

</div>

{% endblock content %}

src/templates/management/company_list.html
{% extends 'base.html' %}
{% load static %}

{% block css_links %}
{% endblock css_links %}

{% block top %}
<div class="d-flex flex-row bd-highlight mb-3 justify-content-between">
    <div>
        <h4> Company List </h4>
    </div>
    <div class="">
        <a href="{% url 'supplier:company_create' %}" class="btn btn-primary ml-3 float-end">Create Company</a>
    </div>
</div>
{% endblock top %}

{% block content %}

<div class="search-results-wrapper mt-3">
    <table class="table table-hover table-sm">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody id="search-results">
            {% for item in object_list %}
            <tr >
                <th>
                    # {{ item.id }}
                </th>
                <td>
                    {{ item.name }}
                </td>
                <td>
                    {% if item.is_active %}
                        <span class="text-success">Active</span>
                    {% else %}
                        <span class="text-danger">Inactive</span>
                    {% endif %}
                </td>
                <td>
                    {% if item.is_active %}
                        <a href="{% url 'supplier:company_disable' item.id %}" class="btn btn-outline-danger btn-sm"> Disable </a>
                    {% else %}
                        <a href="{% url 'supplier:company_disable' item.id %}" class="btn btn-outline-danger btn-sm"> Enable </a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

{% block js_links %}
{% endblock js_links %}

src/templates/management/create_logistics_staff.html
{% extends 'base.html' %}
{% load static %}

{% block top %}
    <div>
        <h4> Create Logistics Staff </h4>
    </div>
{% endblock top %}

{% block content %}



{% endblock content %}

src/templates/management/disable_logistics_staff.html
{% extends 'base.html' %}
{% load static %}

{% block top %}
    <div class="d-flex flex-row bd-highlight mb-3 justify-content-between">
        <div>
            <h4> Disable Logistics Staff </h4>
        </div>
    </div>
{% endblock top %}

{% block content %}

{% block content %}
<div class="d-flex">
    <div class="detail-area">
        <form method="Post" action=".">
            {% csrf_token %}
            {{ form|crispy }}

                <a href="{% url 'event:dashboard' object.slug %}" class="btn btn-outline-primary mt-3">Cancel</a>
                <input class="btn btn-danger mt-3" type="submit" name="submit" value="Submit">

        </form>
    </div>

</div>

{% endblock content %}

src/templates/management/manager_options.html
{% extends 'base.html' %}
{% load static %}

{% block top %}
<div class="d-flex flex-row bd-highlight mb-3 justify-content-between">
    <div>
        <h4> Manager Options </h4>
    </div>
</div>
{% endblock top %}
{% block content %}

<h4 class="my-3"> Company </h4>
<div class="list-group">
    <a href="#" class="list-group-item list-item-group-action list-group-item">Create Company ></a>
    <a href="#" class="list-group-item list-item-group-action list-group-item">Update Company ></a>
    <a href="#" class="list-group-item list-item-group-action list-group-item">Disable Company ></a>
</div>
<h4 class="my-3"> Logistics Users </h4>
<div class="list-group">
    <a href="#" class="list-group-item list-item-group-action list-group-item">Create User ></a>
    <a href="#" class="list-group-item list-item-group-action list-group-item">Update User ></a>
    <a href="#" class="list-group-item list-item-group-action list-group-item">Disable User ></a>
</div>


{% endblock content %}