src/api/urls.py
from django.urls import path
from .views import Worker_List, CheckStaffPayrollID

app_name = 'api'

urlpatterns = [
    path('worker/<int:event_id>/<str:name>', Worker_List, name='worker_list'),
    path('worker/payroll/<str:payroll_id>/', CheckStaffPayrollID, name='worker_payroll_id'),
]

src/event/urls.py
from django.urls import path
import event.views as v_

app_name = 'event'

urlpatterns = [
    path('', v_.EventListView.as_view(), name='event_list'),
#   Managers
    path('management/', v_.ManagerOptions.as_view(), name='manager_options'),
#   Event
    path('create/', v_.EventCreateView.as_view(), name='create_event'),
    path('<slug:slug>/', v_.EventDetailView.as_view(), name='dashboard'),
    path('<slug:slug>/assign-supplier/', v_.EventAssignSupplier.as_view(), name='assign_supplier'),
    path('<slug:slug>/assign-logistics-user/', v_.EventAssignLogisticsStaff.as_view(), name='assign_logistics_user'),
    path('<slug:slug>/close-event/', v_.EventCloseView.as_view(), name='close_event'),
#   Worker urls below this line
    path('<slug:slug>/worker/', v_.WorkerSearch.as_view(), name='worker_search'),
    path('<slug:slug>/worker/create/', v_.WorkerCreate.as_view(), name='worker_create'),
    path('<slug:slug>/worker/bulk-create/', v_.WorkerBulkCreate.as_view(), name='worker_bulk_create'),
    path('<slug:slug>/worker/<int:id>/', v_.WorkerDetail.as_view(), name='worker_detail'),
    path('<slug:slug>/worker/<int:id>/edit/', v_.WorkerUpdate.as_view(), name='worker_update'),
    path('<slug:slug>/worker/<int:id>/accredit/', v_.WorkerAccredit.as_view(), name='worker_accredit'),
]

src/festival_accreditation/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('company/', include('supplier.urls', namespace='supplier')),
    path('event/', include('event.urls', namespace='event')),
    path('api/', include('api.urls', namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/worker/bulk_worker_upload.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css_links %}
    <link rel="stylesheet" href="{% static 'css/worker_details.css' %}">
{% endblock css_links %}

{% block top %}
<div class="d-flex flex-row bd-highlight mb-3 justify-content-between">
    <div>
        <h4>Create Workers - Bulk</h4>
    </div>
</div>
{% endblock top %}
{% block content %}
<div class="d-flex">
    <div class="detail-area">
        <form method="Post" action="." enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}

                <a href="{% url 'event:dashboard' object.slug %}" class="btn btn-outline-primary mt-3">Cancel</a>
                <input class="btn btn-danger mt-3" type="submit" name="submit" value="Submit">

        </form>
    </div>

</div>


{% endblock content %}

src/templates/worker/worker_accredit.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css_links %}
    <link rel="stylesheet" href="{% static 'css/worker_accredit.css' %}">
{% endblock css_links %}

{% block top %}
    <div>
        <h4> {{object.first_name}} {{object.last_name}} - Accredit</h4>
    </div>
{% endblock top %}

{% block content %}
<div class="d-flex justify-content-between">
    <div class="d-flex flex-column justify-content-between">
        <div class="detail-area" id="accredit__form-wrapper">
            <form action="." method="POST">

                {% csrf_token %}
                {{accredit | crispy }}
                <!-- tent | crispy  -->
                {{wristband | crispy }}
                {% if object.working_at.bib_required %}
                    {{bib | crispy }}
                {% endif %}
            
                <a href="{% url 'event:worker_detail' slug=object.working_at.slug id=object.id %}" class="btn btn-outline-primary mt-3">Cancel</a>
                <button id="booth__modal-btn" type="button" class="btn btn-primary mt-3" data-bs-toggle="modal" data-bs-target="#booth__modal">
                  Photo
                </button>
                <input type="submit" value="Submit" name="submit" class="btn btn-outline-danger mt-3" id="form-submit" hidden>
            </form>
        </div>
    </div>    
    <div class="avatar booth">
            <canvas id="canvas" width="450" height="500"></canvas>
            <img id="photo" src="{% static 'img/avatar.png' %}" alt="You" class="img-fluid avatar">    
            <div class="modal fade" id="booth__modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="booth_modalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title">Festival Accreditation</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <video id="video" width="450" height="500" class="img-fluid"></video>
                  </div>
                  <div class="modal-footer">
                    <button type="button" id="capture" class="booth-capture-button btn btn-primary btn-block">Take Photo</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
    </div>
</div>
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Festival Accreditation</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>No camera detected! Please connect camera to complete.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
</div>

{% endblock content %}

{% block js_links %}
    <script src="{% static 'js/accredit.js' %}" type="text/javascript"></script>
{% endblock js_links %}

src/templates/worker/worker_create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css_links %}
{% endblock css_links %}

{% block top %}
<div class="d-flex flex-row bd-highlight mb-3 justify-content-between">
    <div>
        <h4> Create New Worker</h4>
    </div>
</div>
{% endblock top %}
{% block content %}
<div class="d-flex">
    <div class="detail-area">
        <form method="Post" action=".">
            {% csrf_token %}
            {{ form|crispy }}
                <button id='backBtn' class="btn btn-outline-primary mt-3">Cancel</button>
                <input class="btn btn-danger mt-3" type="submit" name="submit" value="Submit">

        </form>
    </div>
</div>

{% endblock content %}

{% block js_links %}
    <script src="{% static 'js/worker-create.js' %}" type="text/javascript"></script>
{% endblock js_links %}

src/templates/worker/worker_details.html
{% extends 'base.html' %}
{% load static %}

{% block top %}
<div>
    <h4> {{object.first_name}} {{object.last_name}}</h4>
</div>     
{% endblock top %}

{% block content %}
<div class="d-flex justify-content-between">
    <div class="d-flex flex-column justify-content-between">
        <div class="detail-area">
            <div class="bg-darker rounded d-flex border mb-2">
                <div class="bg-transparent left p-1">Date Of Birth:</div>
                <div class="bg-white text-dark right p-1 rounded-end">{{object.date_of_birth}}</div>
            </div>
            <div class="bg-darker rounded d-flex border mb-2">
                <div class="bg-transparent left p-1">SIA No:</div>
                <div class="bg-white text-dark right p-1 rounded-end">{{object.sia_no}}</div>
            </div>
            <div class="bg-darker rounded d-flex border mb-2">
                <div class="bg-transparent left p-1">SIA Expiry:</div>
                <div class="bg-white text-dark right p-1 rounded-end">{{object.sia_exp}}</div>
            </div>
            <div class="bg-darker rounded d-flex border mb-2">
                <div class="bg-transparent left p-1">Employer:</div>
                <div class="bg-white text-dark right p-1 rounded-end">{{object.employer}}</div>
            </div>
            <div class="bg-darker rounded d-flex border mb-2">
                <div class="bg-transparent left p-1">Working At:</div>
                <div class="bg-white text-dark right p-1 rounded-end">{{object.working_at}}</div>
            </div>
        </div>
        {% if object.is_approved %}
        <div class="detail-area">
            <div class="bg-success rounded p-2 text-white"> Approved {{ object.when_approved }} by {{object.approved_by | title}}</div>
        </div>
        {% endif %}
    </div>    
    <div class="avatar">
        {% if object.get_accreditation.get_image_url%}
            <image class="img-fluid avatar" src="{{object.get_accreditation.get_image_url}}">
        {% else %}
            <image class="img-fluid avatar" src="{% static 'img/avatar.png' %}">
        {% endif %}

    </div>
</div>
<div class="mt-3">
        <a href="{% url 'event:worker_search' slug=object.working_at.slug %}" class="btn btn-outline-primary">Back</a>
    {% if object.can_be_approved %}
        <a href="{% url 'event:worker_update' slug=object.working_at.slug id=object.id%}" class="btn btn-outline-primary">Edit</a>
        <a href="{% url 'event:worker_accredit' slug=object.working_at.slug id=object.id%}" class="btn btn-outline-danger">Accredit</a>
    {% endif %}
</div>

{% endblock content %}

src/templates/worker/worker_edit.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css_links %}
    <link rel="stylesheet" href="{% static 'css/worker_details.css' %}">
{% endblock css_links %}

{% block top %}
    <div>
        <h4> {{object.first_name}} {{object.last_name}}</h4>
    </div>
{% endblock top %}

{% block content %}
<div class="d-flex">
    <div class="detail-area">
        <form method="Post" action=".">
            {% csrf_token %}
            {{ form|crispy }}

                {% comment %} <a href="{% url 'event:worker_detail' slug=object.working_at.slug id=object.id %}" class="btn btn-outline-primary mt-3">Cancel</a> {% endcomment %}
                <button id='backBtn' class="btn btn-outline-primary mt-3">Cancel</button>
                <input class="btn btn-danger mt-3" type="submit" name="submit" value="Submit">

        </form>
    </div>

</div>

{% endblock content %}
{% block js_links %}
    <script src="{% static 'js/worker-create.js' %}" type="text/javascript"></script>
{% endblock js_links %}

src/templates/worker/worker_search.html
{% extends 'base.html' %}
{% load static %}

{% block css_links %}
{% endblock css_links %}

{% block top %}
<div class="d-flex flex-row bd-highlight mb-3 justify-content-between">
    <div>
        <h4 id="subTitle">{{object.name}} - Worker Search </h4>
    </div>
    <div>
        <a href="{% url 'event:worker_create' object.slug %}" class="btn btn-outline-primary ml-3">
            Add Staff
        </a>
    </div>
</div>
{% endblock top %}
{% block content %}
<div class="search-wrapper d-flex justify-content-between">
    <form class="d-flex w-75" action="." method="get" id="search-form">
        <input class="form-control me-2" type="search" placeholder="Enter the worker surname..." aria-label="Search" name="search-value" data-event-id="{{object.id}}" autofocus>
        <button class="btn btn-primary" type="submit" id="worker-search-btn">
            Search
        </button>
    </form>
</div>

<div class="search-results-wrapper mt-3">
    <table class="table table-hover table-sm">
        <thead>
            <tr>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">D.O.B</th>
                <th scope="col">Employer</th>
            </tr>
        </thead>
        <tbody id="search-results">
            <tr >
                <td colspan='4'>
                    No results...
                </td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock content %}

{% block js_links %}
    <script src="{% static 'js/worker-search.js' %}" type="text/javascript"></script>
{% endblock js_links %}