src/api/urls.py
from django.urls import path
from .views import Worker_List, CheckStaffPayrollID

app_name = 'api'

urlpatterns = [
    path('worker/<int:event_id>/<str:name>', Worker_List, name='worker_list'),
    path('worker/payroll/<str:payroll_id>/', CheckStaffPayrollID, name='worker_payroll_id'),
]

src/event/urls.py
from django.urls import path
import event.views as v_

app_name = 'event'

urlpatterns = [
    path('', v_.EventListView.as_view(), name='event_list'),
#   Managers
    path('management/', v_.ManagerOptions.as_view(), name='manager_options'),
#   Event
    path('create/', v_.EventCreateView.as_view(), name='create_event'),
    path('<slug:slug>/', v_.EventDetailView.as_view(), name='dashboard'),
    path('<slug:slug>/assign-supplier/', v_.EventAssignSupplier.as_view(), name='assign_supplier'),
    path('<slug:slug>/assign-logistics-user/', v_.EventAssignLogisticsStaff.as_view(), name='assign_logistics_user'),
    path('<slug:slug>/close-event/', v_.EventCloseView.as_view(), name='close_event'),
#   Worker urls below this line
    path('<slug:slug>/worker/', v_.WorkerSearch.as_view(), name='worker_search'),
    path('<slug:slug>/worker/create/', v_.WorkerCreate.as_view(), name='worker_create'),
    path('<slug:slug>/worker/bulk-create/', v_.WorkerBulkCreate.as_view(), name='worker_bulk_create'),
    path('<slug:slug>/worker/<int:id>/', v_.WorkerDetail.as_view(), name='worker_detail'),
    path('<slug:slug>/worker/<int:id>/edit/', v_.WorkerUpdate.as_view(), name='worker_update'),
    path('<slug:slug>/worker/<int:id>/accredit/', v_.WorkerAccredit.as_view(), name='worker_accredit'),
]

src/festival_accreditation/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('company/', include('supplier.urls', namespace='supplier')),
    path('event/', include('event.urls', namespace='event')),
    path('api/', include('api.urls', namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/event/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.base import ContentFile
from event.forms import AccreditForm, BibForm, BulkCreateWorkerForm, CreateWorker, EventAssignSuppliersForm, EventForm, EventAssignLogisticsUserForm, WristBandForm
from django.db.models import F, Count, When, Value, Case, Sum
from django.views.generic import ListView, DetailView, CreateView, UpdateView, TemplateView
from django.views import View
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from .models import Event, Worker, Accredit, Tent, WorkerImage, Role
from account.mixins import IsManagerMixin, IsAuthorisedMixin

import base64
import datetime

class EventCreateView(LoginRequiredMixin, IsManagerMixin, CreateView):
    template_name = 'event/create_event.html'
    model = Event
    form_class = EventForm

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('event:dashboard', kwargs={'slug': self.object.slug})    

class EventListView(LoginRequiredMixin, ListView):
    template_name = 'event/event_list.html'
    queryset = Event.objects.all()

class EventDetailView(LoginRequiredMixin,IsAuthorisedMixin, DetailView):
    template_name = 'event/dashboard.html'
    model = Event

    def get_object(self):
        slug_ = self.kwargs.get('slug')
        return get_object_or_404(Event, slug=slug_)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        event = self.get_object()
        context['accredit_by_company_sum'] = Accredit.objects.filter(worker__working_at = event.id).values(name=F('worker__employer__name')).annotate(num_workers=Count('id'))
        context['accredit_by_role_sum'] = Role.objects.all().annotate(num_workers=Sum(Case(When(accredit__worker__working_at = event.id, then=Value(1)),default=Value(0),)))
        context['summary'] = Worker.objects.filter(working_at=event.id).values(name=F('employer__name')).annotate(worker_count=Count('id')).annotate(workers_accreditted=Count('accredit__id'))
        return context

class EventCloseView(LoginRequiredMixin, IsManagerMixin, UpdateView):
    template_name = 'event/close_event.html'
    model = Event
    fields = ['is_active']
    
    def get_object(self):
        slug_ = self.kwargs.get('slug')
        return get_object_or_404(Event, slug=slug_)

    def get_success_url(self):
        return reverse_lazy('event:dashboard', kwargs={'slug': self.object.slug})

class EventAssignSupplier(LoginRequiredMixin, IsManagerMixin, UpdateView):
    template_name = 'event/assign_company.html'
    model = Event
    form_class = EventAssignSuppliersForm

    def get_object(self):
        slug_ = self.kwargs.get("slug")
        return get_object_or_404(Event, slug=slug_)

    def get_success_url(self):
        return reverse_lazy('event:dashboard', kwargs={'slug': self.object.slug})

class EventAssignLogisticsStaff(LoginRequiredMixin, IsManagerMixin, UpdateView):
    template_name = 'event/assign_logistics_staff.html'
    model = Event
    form_class = EventAssignLogisticsUserForm

    def get_object(self):
        slug_ = self.kwargs.get("slug")
        return get_object_or_404(Event, slug=slug_)

    def get_success_url(self):
        return reverse_lazy('event:dashboard', kwargs={'slug': self.object.slug})

class WorkerSearch(LoginRequiredMixin, View):

    template_name = 'worker/worker_search.html'

    def get_object(self):
        slug_ = self.kwargs.get('slug')
        return get_object_or_404(Event, slug=slug_)

    def get(self, request, *args, **kwargs):
        object = self.get_object()
        context = {
            'object':object,
        }
        return render(request, self.template_name, context)

class WorkerCreate(LoginRequiredMixin, CreateView):
    template_name = 'worker/worker_create.html'
    model = Worker
    form_class = CreateWorker

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        event = Event.objects.get(slug=self.kwargs.get('slug'))
        context['object'] = event
        return context

    def get_form_kwargs(self):
        kwargs = super(WorkerCreate, self).get_form_kwargs()
        kwargs['slug'] = self.kwargs.get('slug')
        return kwargs

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        event = Event.objects.get(slug=self.kwargs.get('slug'))
        form.instance.working_at = event
        return super().form_valid(form)

class WorkerBulkCreate(LoginRequiredMixin, IsManagerMixin, CreateView):
    template_name = 'worker/bulk_worker_upload.html'
    form_class = BulkCreateWorkerForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        event = Event.objects.get(slug=self.kwargs.get('slug'))
        context['object'] = event
        return context

    def get_form_kwargs(self):
        kwargs = super(WorkerBulkCreate, self).get_form_kwargs()
        kwargs['slug'] = self.kwargs.get('slug')
        return kwargs

    def form_valid(self, form):
        form.instance.uploaded_by_user = self.request.user
        form.instance.event = Event.objects.get(slug=self.kwargs.get('slug'))
        messages.success(self.request, 'File uploaded')
        return super().form_valid(form)


class WorkerDetail(LoginRequiredMixin, DetailView):
    template_name = 'worker/worker_details.html'
    model = Worker

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Worker, id=id_)

class WorkerUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'worker/worker_edit.html'
    model = Worker
    form_class = CreateWorker

    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(Worker, id=id_)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['slug'] = self.kwargs.get('slug')
        return kwargs

    def get_success_url(self):
        return reverse_lazy('event:worker_detail', kwargs={'id': self.object.id, 'slug': self.object.working_at.slug})

class WorkerAccredit(LoginRequiredMixin, View):
    template_name = 'worker/worker_accredit.html'
    acccreditForm = AccreditForm
    wristbandForm = WristBandForm
    bibForm = BibForm

    def get_time(self):
        time_now = datetime.datetime.now()
        return time_now.strftime('%I%M')

    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(Worker, id=id_)

    def get(self, request, *args, **kwargs):
        object = self.get_object()
        try: 
            if object.is_approved:
                messages.warning(request, 'Staff member already accredited')
                return redirect(object.get_absolute_url())
        except Accredit.DoesNotExist:
            pass

        bib = None
        if object.working_at.bib_required:
            bib = self.bibForm
        context = {
            'object': object,
            'accredit': self.acccreditForm,
            'wristband': self.wristbandForm,
            'bib': bib,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):

        accredit = self.acccreditForm(request.POST)
        wristband = self.wristbandForm(request.POST)

        if accredit.is_valid() and wristband.is_valid():
            new_accredit = accredit.save(commit=False)
            new_wristband = wristband.save(commit=False)
            
            # process forms
            new_wristband.save()
            if accredit.cleaned_data['camping']:
                new_tent = Tent(tent_tag = accredit.cleaned_data['tent_tag'], tent_tag_colour = accredit.cleaned_data['tent_tag_colour'])
                new_tent.save()
                new_accredit.tent = new_tent

            new_accredit.approved_by = request.user
            new_accredit.worker = self.get_object()
            new_accredit.wristband = new_wristband

            new_accredit.is_complete = True
            new_accredit.save()

            photo = accredit.cleaned_data['mugshot']
            image_data = base64.b64decode(photo)
            new_worker_image = WorkerImage()
            new_worker_image.image.save(f"{new_accredit.worker}{self.get_time()}.png", ContentFile(image_data), save=False)
            new_worker_image.accredit = new_accredit
            new_worker_image.save()

            # process bib and or images then add to accredit

            return redirect(self.get_object().get_absolute_url())
        return render(request,self.template_name,{'accredit':accredit, 'wristband': wristband, 'object':self.get_object()})


class ManagerOptions(LoginRequiredMixin, TemplateView):
    template_name = 'management/manager_options.html'

    def get(self, request, *args, **kwargs):

        return render(request, self.template_name,{})

src/templates/event/assign_company.html
{% extends 'base.html' %}
{% load static %}

{% block top %}
<div class="d-flex flex-row bd-highlight mb-3 justify-content-between">
    <div>
        <h4> {{object.name}} - Assign Company </h4>
    </div>
</div>
{% endblock top %}
{% block content %}
    <form action="." method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <a href='{% url "event:dashboard" object.slug %}' class='btn btn-outline-primary'>Cancel</a>
        <input class='btn btn-danger' type="submit" name="assign_supplier" value="Submit"/>
    </form>

{% endblock content %}

src/templates/event/assign_logistics_staff.html
{% extends 'base.html' %}
{% load static %}

{% block top %}
<div class="d-flex flex-row bd-highlight mb-3 justify-content-between">
    <div>
        <h4> {{object.name}} - Assign Users </h4>
    </div>
</div>
{% endblock top %}

{% block content %}
<form action="." method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <a href='{% url "event:dashboard" object.slug %}' class='btn btn-outline-primary'>Cancel</a>
    <input class='btn btn-danger' type="submit" name="assign_staff" value="Submit"/>
</form>


{% endblock content %}

src/templates/event/close_event.html
{% extends 'base.html' %}
{% load static %}

{% block top %}
<div class="d-flex flex-row bd-highlight mb-3 justify-content-between">
    <div>
        <h4> {{object.name}} - Close Event </h4>
    </div>
</div>
{% endblock top %}
{% block content %}
<form action='.' method='post'>
    {% csrf_token %}
    <p>Are you sure you would like to close this event?*</p>
    <a href='{% url "event:dashboard" slug=object.slug %}' class='btn btn-outline-primary' id='cancel'>Cancel</a>
    <input class='btn btn-danger' type='submit' name='accept' value='Accept'>
    <p class='small text-muted'>*You will no longer be able to accredit staff.</p>
</form>
{% endblock content %}

src/templates/event/create_event.html
{% extends 'base.html' %}
{% load static %}

{% block css_links %}
    <link rel="stylesheet" href="{% static 'css/worker_details.css' %}">
{% endblock css_links %}

{% block top %}
    <div>
        <h4> Create Event </h4>
    </div>
{% endblock top %}

{% block content %}

<div class="d-flex">
    <div class="d-flex flex-column justify-content-between">
        <div class="detail-area">
            <form action="." method="POST">
                {% csrf_token %}
                {{ form.as_p}}
                <a href="{% url 'event:event_list' %}" class="btn btn-outline-primary">Cancel</a>
                <input class="btn btn-danger" type="submit" name="create_event" value="Submit"/>
            </form>
        </div>
    </div>
    <div class="detail-area">

    </div>
</div>


{% endblock content %}

src/templates/event/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block css_links %}
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">    
{% endblock css_links %}

{% block top %}
<div class="d-flex bd-highlight mb-3 justify-content-between">
    <div>
        <h4> {{object.name}} - Dashboard </h4>
    </div>
    <div>
        <h4 style='font-size: 1.2em'> Status: {% if object.is_active %} <span class="text-success">Active</span> {% else %} <span class="text-danger">Inactive</span> {% endif %}</h4>
    </div>
</div>
{% endblock top %}

{% block content %}
<div class="d-flex flex-row justify-content-between">
    <!-- <div> -->
        <!-- <p>Staff Accredited By Role</p> -->
        <div class="card border-primary" style="max-width: 30rem;">
            <div class="card-header text-white bg-primary">
                <h4 class="card-title">Staff Accredited By Role</h4>
            </div>
            <div class="card-body">
                <!-- <h4>Staff Accredited By Role</h4> -->
                <table class="table table-hover table-sm">
                    <thead>
                        <tr>
                            <th scope="col">Role</th>
                            <th scope="col">Count</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for role in accredit_by_role_sum %}
                        <tr>
                            <th scope="row">{{role.name}}</th>
                            <td style="text-align: center;">{{role.num_workers}}</td>
                        </tr>
                        {% empty %}
                        <p>No staff have been accredited. <br/>
                            Click on staff search to begin<br/>
                            accrediting staff.</p>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    <!-- </div> -->
    
    <div class="card border-primary" style="max-width: 30rem;">
        <div class="card-header text-white bg-primary">
            <h4 class="card-title">Summary</h4>
        </div>
        <div class="card-body">
            <!-- <h4>Summary of accredited staff</h4> -->
            <table class="table table-hover table-sm">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Booked</th>
                        <th scope="col">
                            Accredit
                        </th>
                    </tr>
                </thead>
                <tbody>
                {% for com in summary %}
                    <tr>
                        <th scope="row">{{com.name}}</th>
                        <td style="text-align: center;">{{com.worker_count}}</td>
                        <td style="text-align: center;">{{com.workers_accreditted}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>

<h4 class="my-3"> Staffing </h4>
<p>Create staff records for this event.</p>
<div class="option-holder">
    <a href="{% url 'event:worker_create' object.slug %}" class="option mt-3 w-25">
        <span class="option-label">Staff Create</span>
        <div class="triangle border-white"></div>
    </a>
    {% comment %} <a href="{% url 'event:worker_bulk_create' object.slug %}" class="option mt-3 w-25">
        <span class="option-label">Staff Bulk Create</span>
        <div class="triangle border-white"></div>
    </a> {% endcomment %}
    <a href="{% url 'event:worker_search' object.slug %}" class="option mt-3 w-25">
        <span class="option-label">Staff Search</span>
        <div class="triangle border-white"></div>
    </a>
</div>

<h4 class="my-5"> Settings </h4>
<div class="d-flex flex-row justify-content-between">
    <div class="card border-primary" style="width: 18rem;">
        <div class="card-header">
            <h5 class="card-title">Assign Users To Project</h5>
        </div>
        <div class="card-body">
            <p class="card-text">Select which system users are allowed to access this event.</p>
            <a href="{% url 'event:assign_logistics_user' object.slug %}" class="btn btn-outline-primary">Select</a>
        </div>
    </div>
    <div class="card border-primary" style="width: 18rem;">
    <div class="card-header">
        <h5 class="card-title">Assign Company To Project</h5>
    </div>
    <div class="card-body">
        <p class="card-text">Select suppliers expected for this event.</p>
        <a href="{% url 'event:assign_supplier' object.slug %}" class="btn btn-outline-primary">Select</a>
    </div>
    </div>

    <div class="card border-primary" style="width: 18rem;">
        <div class="card-header">
            <h5 class="card-title">Closed Event</h5>
        </div>
        <div class="card-body">
            <p class="card-text">Mark event as inactive. This will stop anymore staff from being accredited.</p>
            <a href="{% url 'event:close_event' slug=object.slug %}" class="btn btn-outline-danger">Close</a>
        </div>
    </div>
</div>
{% endblock content %}

src/templates/event/event_list.html
{% extends 'base.html' %}
{% load static %}

{% block top %}
<div class="d-flex flex-row bd-highlight mb-3 justify-content-between">
    <div>
        <h4> Event List </h4>
    </div>
    <div>
      <a href="{% url 'event:create_event' %}" class="btn btn-primary float-end"> New Event </a>
    </div>
</div>
{% endblock top %}

{% block content %}
<table class="table">
  <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Date</th>
        <th scope="col">Status</th>
        <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for obj in object_list %}
    <tr>
        <th scope="row">{{obj.id}}</th>
        <td>{{obj.name}}</td>
        <td>{{obj.date}}</td>
        {% if obj.is_active %}
          <td>Active</td>
        {% else %}
          <td>Inactive</td>
        {% endif %}
        <td><a href="{{obj.get_absolute_url}}" class="btn btn-outline-primary btn-sm" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Select Event">  View  </a></td>
    </tr>
    {% empty %}
    <tr>
        <th scope="row" >#</th>
        <td colspan="3">Sorry, no events active please speak to the logistics manager.</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}

src/templates/event/update_event.html
{% extends 'base.html' %}
{% load static %}

{% block top %}
    <div>
        <h4> Update Event </h4>
    </div>
{% endblock top %}

{% block content %}



{% endblock content %}